---
    # Install Common Packages 
- name: Deploy lamp stack application
  hosts: all
  become: yes
  roles:
  - common

    # Install and Configure Database
- name: Deploy lamp stack application
  hosts: lamp-db
  become: yes
  roles:
  - mysql

    # Install and Configure Web Service
- name: Deploy lamp stack application
  hosts: lamp-web
  become: yes
  roles: 
  - name: httpd-php
